name: addition
on: [push]
jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11","3.12"]
    steps:
      - uses: action/checkout@v4.1.4
      - name: Set up python ${{matrix.paython-version }}
        uses: action/set-python@v5
        with:
          python-version: ${{matrix.paython-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest
      - name: Run test
        run: |
          cd app
          python -m pytest addition.py
  
